### ISSUE TITLE
Cleanup cleanups that make cleanups

### ISSUE THREAD

**Issue by Nickuhhh** [howmanysmall/Janitor#1]
During cleanup, the Maid class will keep iterating throughout all tasks until they are all cleaned up. This takes care of cases where a cleanup function will create another cleanup. Imo, there really shouldn't be cleanup functions making cleanup functions in the first place, but it's a feature to consider.

**Comment by howmanysmall** [comment]
...this hurts my brain to read, I'll take a look tomorrow when i'm not confused as hell
